### ISSUE TITLE
关于光平面标定中的图像畸变考虑问题

### ISSUE THREAD

**Issue by pengtao1111** [lianchengyue/calib_laser_planer#1]
您好，看了您的代码，您在光平面标定的过程中直接使用了每个标定板的位姿(R,t),您考虑过此时的(R,t)是没有经过畸变校正的值，还是经过畸变校正后的值？另外，还有您在光平面标定的过程中也没有考虑过图像的畸变问题，这样得到的结果能保证是正确的嘛？

**Comment by lianchengyue** [comment]
你好，确实没有加上，因为我用的工业相机所以影响不大，稍后我更新一下。
如果着急用的话你可以直接读取去畸变之后的图作为输入

**Comment by pengtao1111** [comment]
能加个QQ或者微信嘛。我一直有点疑问。可以向你请教下。QQ453740306

**Comment by pengtao1111** [comment]
另外如果直接使用畸变校正后的图像作为输入，还使用标定时的（R，t）这样使用存在问题嘛？

**Comment by lianchengyue** [comment]
> 能加个QQ或者微信嘛。我一直有点疑问。可以向你请教下。QQ453740306

你好，可以加我的技术讨论群:480534217

**Comment by lianchengyue** [comment]
> 您好，看了您的代码，您在光平面标定的过程中直接使用了每个标定板的位姿(R,t),您考虑过此时的(R,t)是没有经过畸变校正的值，还是经过畸变校正后的值？另外，还有您在光平面标定的过程中也没有考虑过图像的畸变问题，这样得到的结果能保证是正确的嘛？

提交0006解决了该问题。
提交节点:  commit a3f2c75f7eb80baaa1afe2f47d227ee3731d329f
内容:  1:取消了标定过程，使用remap之后的去畸变图像进行处理；
           2:重写了代码让更整洁。
